bash regenie_fit_chr1.sh
bash regenie_fit_chr2.sh
bash regenie_fit_chr3.sh
bash regenie_fit_chr4.sh
bash regenie_fit_chr5.sh
bash regenie_fit_chr6.sh
bash regenie_fit_chr7.sh
bash regenie_fit_chr8.sh
bash regenie_fit_chr9.sh
bash regenie_fit_chr10.sh
bash regenie_fit_chr11.sh
bash regenie_fit_chr12.sh
bash regenie_fit_chr13.sh
bash regenie_fit_chr14.sh
bash regenie_fit_chr15.sh
bash regenie_fit_chr16.sh
bash regenie_fit_chr17.sh
bash regenie_fit_chr18.sh
bash regenie_fit_chr19.sh
bash regenie_fit_chr20.sh
bash regenie_fit_chr21.sh
bash regenie_fit_chr22.sh