bash regenie_test_chr1.sh
bash regenie_test_chr2.sh
bash regenie_test_chr3.sh
bash regenie_test_chr4.sh
bash regenie_test_chr5.sh
bash regenie_test_chr6.sh
bash regenie_test_chr7.sh
bash regenie_test_chr8.sh
bash regenie_test_chr9.sh
bash regenie_test_chr10.sh
bash regenie_test_chr11.sh
bash regenie_test_chr12.sh
bash regenie_test_chr13.sh
bash regenie_test_chr14.sh
bash regenie_test_chr15.sh
bash regenie_test_chr16.sh
bash regenie_test_chr17.sh
bash regenie_test_chr18.sh
bash regenie_test_chr19.sh
bash regenie_test_chr20.sh
bash regenie_test_chr21.sh
bash regenie_test_chr22.sh